In [3]:
set1:set = {1,6,7,8,9,5,9,0}  #set 裡面的資料不能重複，重複會被移除
# 多一個: 可以明確告訴型別
# set. 可以跳出可以用的方法(?)
set1


{0, 1, 5, 6, 7, 8, 9}

Would you like Visual Studio Code to periodically run "git fetch"?
fetch:擷取
=> repo 內有甚麼則強制拉進來；自動把 repo 裡面的資料抓一份進來，自動在不同瀏覽器 or VScode 中執行

In [4]:
set2 = set1
set2
set2.add(12)
set2

{0, 1, 5, 6, 7, 8, 9, 12}

In [5]:
for value in set2:  # 要用 for 把裡面的值一個一個抓出來
    print(value)

0
1
5
6
7
8
9
12


齒輪> 找: 命令選擇區>  打 codespace (show 所有與 codespace 有關的指令)  
or Ctrl shift p > 叫出命令選擇區  
pip install --upgrade numpy

google numpy  
documentation  
api reference  
routines  
array creation routines   
只有numpy說明書上面才有方法的說明  



In [16]:
import numpy as np # 把 numpy 縮寫成 np
array1 = np.array(range(1,11)) # 先用array1接收，之後才能看裡面的值是甚麼
array1:np.ndarray # ndarray
array1:np.ndarray = np.array(range(2,11)) 
array1


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
array2 = array1
array2 + 10*90

array([902, 903, 904, 905, 906, 907, 908, 909, 910])

In [19]:
np.arange(1.3, 3.5, 0.1) # range 只能做整數 / numpy 可以用小數點
# display 只可以在 jupter notebook 裡面執行



array([1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4])

In [24]:
# 如果底下要顯示要用 display
display(np.arange(100.3, 300.5, 0.001) )
display(np.linspace(200,300,20))

array([100.3  , 100.301, 100.302, ..., 300.497, 300.498, 300.499])

array([200.        , 205.26315789, 210.52631579, 215.78947368,
       221.05263158, 226.31578947, 231.57894737, 236.84210526,
       242.10526316, 247.36842105, 252.63157895, 257.89473684,
       263.15789474, 268.42105263, 273.68421053, 278.94736842,
       284.21052632, 289.47368421, 294.73684211, 300.        ])

NumPy reference  
Routines  
Random sampling (numpy.random)  

搜尋: numpy.random.randn
random.randn(d0, d1, ..., dn)  
Return a sample (or samples) from the “standard normal” distribution.  

In [8]:
display(np.random.random())
display(np.random.randn(10,5,3)) # 3D 的亂數資料

0.5921822577666908

array([[[ 1.26703806,  0.67732423, -0.65484131],
        [-1.56649046, -0.32243538,  1.03186136],
        [-1.27152223,  0.29512906, -1.81808166],
        [-1.24312259, -0.00620527,  0.335985  ],
        [-0.90793031, -0.80382143,  0.9424363 ]],

       [[ 0.60879549, -0.79737512,  0.76950152],
        [-2.34721787,  1.54953702,  0.50822905],
        [ 1.00150273, -1.18862299, -0.1878379 ],
        [-1.30563136,  0.21931457,  0.66267164],
        [-0.10383136, -0.66291724,  1.1069117 ]],

       [[-1.09894646,  0.45788653,  1.05209619],
        [-2.15681735, -0.96899847, -1.88190477],
        [ 1.78315255, -1.98398553, -0.84751999],
        [-0.57814276, -0.23478249,  1.87878332],
        [-0.2656875 , -1.48861172,  0.60559257]],

       [[ 0.49994067,  0.54146237,  0.43465024],
        [ 1.30483423,  0.44212298,  0.11815451],
        [-0.86954989, -0.61923032, -0.4610297 ],
        [-0.0102898 , -0.81739307, -0.19496052],
        [ 1.25490675, -0.33630969, -0.39151409]],

       [[-0.

# display(np.random.randint)

 從 numpy 裡面搜尋 randint
=> numpy.random.randint

=> random.randint(low, high=None, size=None, dtype=int)
=> sizeint or tuple of ints, optional
 numpy 產生出來的叫 ndarray (???)

In [15]:
display(np.random.random())
# display(np.random.randn(10,5,3)) # 3D 的亂數資料
display(np.random.randint(1,10,size=(3,4)))

0.9805297267831027

array([[5, 9, 5, 3],
       [3, 5, 2, 8],
       [3, 5, 8, 6]])