In [3]:
set1:set = {1,6,7,8,9,5,9,0}  #set 裡面的資料不能重複，重複會被移除
# 多一個: 可以明確告訴型別
# set. 可以跳出可以用的方法(?)
set1


{0, 1, 5, 6, 7, 8, 9}

Would you like Visual Studio Code to periodically run "git fetch"?
fetch:擷取
=> repo 內有甚麼則強制拉進來；自動把 repo 裡面的資料抓一份進來，自動在不同瀏覽器 or VScode 中執行

In [4]:
set2 = set1
set2
set2.add(12)
set2

{0, 1, 5, 6, 7, 8, 9, 12}

In [5]:
for value in set2:  # 要用 for 把裡面的值一個一個抓出來
    print(value)

0
1
5
6
7
8
9
12


齒輪> 找: 命令選擇區>  打 codespace (show 所有與 codespace 有關的指令)
or Ctrl shift p > 叫出命令選擇區
pip install --upgrade numpy

google numpy /n
documentation /n
api reference /n
routines /n
array creation routines
只有numpy說明書上面才有方法的說明



In [16]:
import numpy as np # 把 numpy 縮寫成 np
array1 = np.array(range(1,11)) # 先用array1接收，之後才能看裡面的值是甚麼
array1:np.ndarray # ndarray
array1:np.ndarray = np.array(range(2,11)) 
array1


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
array2 = array1
array2 + 10*90

array([902, 903, 904, 905, 906, 907, 908, 909, 910])

In [19]:
np.arange(1.3, 3.5, 0.1) # range 只能做整數 / numpy 可以用小數點
# display 只可以在 jupter notebook 裡面執行



array([1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4])

In [24]:
# 如果底下要顯示要用 display
display(np.arange(100.3, 300.5, 0.001) )
display(np.linspace(200,300,20))

array([100.3  , 100.301, 100.302, ..., 300.497, 300.498, 300.499])

array([200.        , 205.26315789, 210.52631579, 215.78947368,
       221.05263158, 226.31578947, 231.57894737, 236.84210526,
       242.10526316, 247.36842105, 252.63157895, 257.89473684,
       263.15789474, 268.42105263, 273.68421053, 278.94736842,
       284.21052632, 289.47368421, 294.73684211, 300.        ])

NumPy reference  
Routines  
Random sampling (numpy.random)  

搜尋: numpy.random.randn